#!/usr/bin/env bash
# ============================================================
# Blue Wallets — First-time setup script
#
# Generates a working .env with strong random secrets and
# optionally generates mTLS certificates.
#
# Run:   ./setup.sh
# ============================================================

set -e

cd "$(dirname "$0")"

echo ""
echo "  ╔══════════════════════════════════════════════════╗"
echo "  ║   Blue Wallets — First-time setup                ║"
echo "  ╚══════════════════════════════════════════════════╝"
echo ""

# ── Check prerequisites ───────────────────────────────────────
missing=""
command -v openssl >/dev/null 2>&1 || missing="$missing openssl"
command -v docker >/dev/null 2>&1 || missing="$missing docker"

if [ -n "$missing" ]; then
  echo "❌ Missing required tools:$missing"
  echo "   Install them first and re-run setup.sh"
  exit 1
fi

# ── Generate .env ─────────────────────────────────────────────
if [ -f .env ]; then
  echo "⚠️  .env already exists."
  read -p "   Overwrite with new random secrets? [y/N] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "   Keeping existing .env"
  else
    rm .env
  fi
fi

if [ ! -f .env ]; then
  echo "🔐 Generating .env with strong random secrets..."
  POSTGRES_PW=$(openssl rand -base64 24 | tr -d '=/+' | head -c 24)
  INTERNAL_KEY=$(openssl rand -hex 32)
  AGENT_KEY=$(openssl rand -hex 32)

  cat > .env <<EOF
# Generated by setup.sh on $(date)
# Do NOT commit this file to git — it contains secrets

POSTGRES_PASSWORD=${POSTGRES_PW}
INTERNAL_AUTH_KEY=${INTERNAL_KEY}
AGENT_AUTH_KEY=${AGENT_KEY}

# Blockchain RPC — change to your provider's URL for production
ETH_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/demo
ETH_CHAIN_ID=11155111

# Restrict CORS origin in production (e.g. https://console.yourbank.internal)
CORS_ORIGIN=

# Logging
LOG_LEVEL=info

# AI Agent (optional)
LLM_MODEL=qwen2.5:7b-instruct
OLLAMA_MEM_LIMIT=16G
OLLAMA_CPU_LIMIT=4
OLLAMA_NUM_PARALLEL=2
EOF
  chmod 600 .env
  echo "   ✅ .env created (mode 600)"
fi

# ── Generate mTLS certs ───────────────────────────────────────
if [ ! -f certs/ca.pem ] || [ ! -f certs/driver-cert.pem ] || [ ! -f certs/console-cert.pem ]; then
  echo ""
  echo "🔏 Generating mTLS certificates..."
  if [ -x ./certs/generate-certs.sh ]; then
    ./certs/generate-certs.sh
  else
    # Fall back to inline cert generation
    mkdir -p certs
    cd certs
    # Root CA
    openssl genrsa -out ca-key.pem 4096 2>/dev/null
    openssl req -new -x509 -days 3650 -key ca-key.pem -out ca.pem \
      -subj "/CN=Blue Wallets CA" 2>/dev/null
    # Driver cert
    openssl genrsa -out driver-key.pem 2048 2>/dev/null
    openssl req -new -key driver-key.pem -out driver.csr \
      -subj "/CN=blue-driver" 2>/dev/null
    openssl x509 -req -in driver.csr -CA ca.pem -CAkey ca-key.pem \
      -CAcreateserial -out driver-cert.pem -days 3650 \
      -extfile <(printf "subjectAltName=DNS:blue-driver,DNS:localhost,IP:127.0.0.1") 2>/dev/null
    # Console cert
    openssl genrsa -out console-key.pem 2048 2>/dev/null
    openssl req -new -key console-key.pem -out console.csr \
      -subj "/CN=blue-console" 2>/dev/null
    openssl x509 -req -in console.csr -CA ca.pem -CAkey ca-key.pem \
      -CAcreateserial -out console-cert.pem -days 3650 \
      -extfile <(printf "subjectAltName=DNS:blue-console,DNS:localhost,IP:127.0.0.1") 2>/dev/null
    rm -f *.csr *.srl
    cd ..
  fi
  echo "   ✅ certs/ generated"
else
  echo "🔏 mTLS certs already exist in certs/ — keeping"
fi

# ── Summary ───────────────────────────────────────────────────
echo ""
echo "╭──────────────────────────────────────────────────────────╮"
echo "│ ✅ Setup complete!                                       │"
echo "│                                                          │"
echo "│ Next steps:                                              │"
echo "│                                                          │"
echo "│   1. Start the core stack:                               │"
echo "│      docker compose -f docker-compose.client.yml up -d   │"
echo "│                                                          │"
echo "│   2. (Optional) Start the AI agent stack:                │"
echo "│      docker compose \\\\                                   │"
echo "│        -f docker-compose.client.yml \\\\                   │"
echo "│        -f docker-compose.agent.yml up -d                 │"
echo "│                                                          │"
echo "│   3. Open the Console:  http://localhost:3400            │"
echo "│      Open the Driver:   https://localhost:443            │"
echo "│                                                          │"
echo "│   Default credentials:                                   │"
echo "│      admin / Admin1234!   (change on first login)        │"
echo "│                                                          │"
echo "│ See DEPLOYMENT_FOR_VISA.md for full setup docs.          │"
echo "╰──────────────────────────────────────────────────────────╯"
echo ""
